plugins {
    id 'multiloader-loader'
    id 'fabric-loom'

    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

def generatedResources = project(":common").file("src/generated/resources")
def commonResources = project(":common").file("src/main/resources")
def changelogFile = rootProject.file("Changelog.md")

repositories {
    flatDir { dir 'libs' }
    maven {
        name = "RyanHCode Maven"
        url = "https://maven.ryanhcode.dev/releases"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    include(modImplementation("foundry.veil:veil-fabric-${minecraft_version}:${veil_version}") {
        exclude group: "maven.modrinth"
        exclude group: "me.fallenbreath"
    })
    include(modApi("dev.ryanhcode.sable-companion:sable-companion-fabric-${project.minecraft_version}:${project.sable_companion_version}"))
    compileOnly("maven.modrinth:DistantHorizonsApi:${dh_api_version}")
    // for some reason fabric HATES distant horizons in a dev environment..... just download the jar and put it in run/mods yourself
//    runtimeOnly("maven.modrinth:DistantHorizons:${dh_version}-${minecraft_version}")
    modApi("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${fcap_version}")
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

sourceSets.main.resources {
    srcDir generatedResources.absolutePath
}

publishMods {
//    dryRun = true
    type = STABLE
    displayName = "[Fabric] Mapwright $project.version"
    setChangelog(changelogFile.text)

    file = remapJar.archiveFile
    modLoaders.add('fabric')

    if (project.hasProperty("mapwrightPushTokenModrinth")) {
        modrinth {
            accessToken = project.property("mapwrightPushTokenModrinth")
            projectId = "iDYmMWwn"
            minecraftVersions.add(minecraft_version)
        }
    }

    if (project.hasProperty("mapwrightPushTokenCurse")) {
        curseforge {
            accessToken = project.property("mapwrightPushTokenCurse")
            projectId = "1361711"
            minecraftVersions.add(minecraft_version)
        }
    }
}