plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'

    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

def generatedResources = project(":common").file("src/generated/resources")
def commonResources = project(":common").file("src/main/resources")
def changelogFile = rootProject.file("Changelog.md")
def modrinthToken = (providers.gradleProperty("mapwrightPushTokenModrinth").orNull ?: System.getenv("MAPWRIGHT_PUSH_TOKEN_MODRINTH") ?: "")
def curseforgeToken = (providers.gradleProperty("mapwrightPushTokenCurse").orNull ?: System.getenv("MAPWRIGHT_PUSH_TOKEN_CURSE") ?: "")

repositories {
    maven {
        name = "RyanHCode Maven"
        url = "https://maven.ryanhcode.dev/releases"
    }
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
            gameDirectory = project.file('runs/client')
        }
        data {
            data()
            gameDirectory = project.file('runs/data')
            programArguments.addAll '--all',
                    '--mod', 'mapwright',
                    '--output', generatedResources.absolutePath,
                    '--existing', commonResources.absolutePath
        }
        server {
            server()
            gameDirectory = project.file('runs/server')
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    jarJar(implementation("foundry.veil:veil-neoforge-${minecraft_version}:${veil_version}") {
        exclude group: "maven.modrinth"
        exclude group: "me.fallenbreath"
    })
    jarJar(api("dev.ryanhcode.sable-companion:sable-companion-common-${project.minecraft_version}:${project.sable_companion_version_range}")) {
        version {
            prefer project.sable_companion_version
        }
    }
    compileOnly("maven.modrinth:DistantHorizonsApi:${dh_api_version}")
    runtimeOnly("maven.modrinth:DistantHorizons:${dh_version}-${minecraft_version}")
}

sourceSets.main.resources {
    srcDir generatedResources.absolutePath
}

publishMods {
//    dryRun = true
    type = STABLE
    displayName = "[NeoForge] Mapwright $project.version"
    setChangelog(changelogFile.text)

    file = jar.archiveFile
    modLoaders.add('neoforge')

    if (!modrinthToken.isEmpty()) {
        modrinth {
            accessToken = modrinthToken
            projectId = "iDYmMWwn"
            minecraftVersions.add(minecraft_version)
        }
    }

    if (!curseforgeToken.isEmpty()) {
        curseforge {
            accessToken = curseforgeToken
            projectId = "1361711"
            minecraftVersions.add(minecraft_version)
        }
    }
}